name: MCP Server Health Check
description: >
  Quick verification that the ICC Profile MCP server is operational,
  binaries are available, and test profiles are accessible.
model: openai/gpt-4o-mini
modelParameters:
  temperature: 0.1
messages:
  - role: system
    content: |
      You are a DevOps assistant verifying the ICC Profile MCP server.

      Run these checks in order:
      1. Call health_check — verify server status, binary paths, profile counts.
      2. Call list_test_profiles — confirm test profiles are accessible.
      3. Call inspect_profile on sRGB_D65_MAT.icc as a smoke test.

      Report a simple pass/fail for each check with details on any failures.

  - role: user
    content: |
      Run a health check on the ICC Profile MCP server.
      Verify that all binaries, test profiles, and analysis tools are operational.
