###############################################################
#
## Copyright (©) 2026 David H Hoyt LLC
#
#
# - 22 SEPT 2026
#
# - Not for PR or FORK Use - obviously
#
###############################################################

name: test-poc
permissions:
  contents: read
  
on:
  workflow_dispatch:

jobs:
  linux:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
    steps:
      - name: Checkout master
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpng-dev libjpeg-dev libtiff-dev libxml2-dev zlib1g-dev libwxgtk3.2-dev libwxgtk-media3.2-dev libwxgtk-webview3.2-dev wx-common wx3.2-headers nlohmann-json3-dev cmake make ninja-build
      - name: CMake Configure
        run: |
          echo "CC=gcc" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV
          git clone https://github.com/InternationalColorConsortium/iccDEV.git
          cd iccDEV/Build
          git branch&&echo ---&&git log --oneline -1
          cmake --preset linux-clang-sanitizers -S Cmake -B . -DSANITIZER_RECOVER=ON
          cmake --build . -j32
          cd ../Testing
          export PATH="$(echo "$PWD"/../Build/Tools/*|tr ' ' :)":$PATH
          export ASAN_OPTIONS='print_scariness=1:halt_on_error=1:detect_leaks=0' UBSAN_OPTIONS="halt_on_error=0:print_stacktrace=1:suppressions=$PWD/silence.txt"
          ./CreateAllProfiles.sh&&./RunTests.sh&&cd HDR&&./mkprofiles.sh&&cd ../Display&&./RunProtoTests.sh&&cd ../hybrid&&./BuildAndTest.sh&&cd ../CalcTest&&./checkInvalidProfiles.sh&&cd ../mcs&&./updateprev.sh&&./updateprevWithBkgd.sh

