###############################################################
#
## Copyright (C) 2024-2025 David H Hoyt. All rights reserved.
##                 https://srd.cx
##
## Last Updated: 01-MAY-2025 1200 EDT by David Hoyt (C)
#
## Intent: windows-11-arm
#
## TODO: Add Unit Test Suite
#
#
#
#
#
#
#
#
#
###############################################################

name: win-check

permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Host System Info
        shell: pwsh
        run: |
          systeminfo
          Write-Host "========= Fetching Deps from Releases... ================`n"
          Start-BitsTransfer -Source "https://github.com/InternationalColorConsortium/iccDEV/releases/download/v2.3.1/vcpkg-exported-deps.zip" -Destination "bitsdeps.zip"
          Write-Host "========= Extracting Dependencies ...    ================`n"
          tar -xf bitsdeps.zip
          ls
          Write-Host "========= Fetching Deps from Releases... ================`n"
          curl -L "https://github.com/InternationalColorConsortium/iccDEV/releases/download/v2.3.1/vcpkg-exported-deps.zip" -o deps.zip
          Write-Host "========= Extracting Dependencies ... ===================`n"
          Expand-Archive -Path "deps.zip" -DestinationPath "deps" -Force
          ls
          Get-CimInstance -ClassName Win32_Processor
          
      - name: Summary Report
        if: always()
        run: |
          echo "### Windows Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "- Status: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
